export default {
    PRESENT_POSITION:"PRESENT_POSITION",
    GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
    GET_PICDROP_DATA:"GET_PICDROP_DATA",
    GET_LOCATION_DATA:"GET_LOCATION_DATA",
    SHOW_HIDE_TIME:"SHOW_HIDE_TIME",
    MATCHED_ROUTE_RESULT:"MATCHED_ROUTE_RESULT",
    SHOW_HIDE_RT:"SHOW_HIDE_RT",
    GET_PICK_DROP_TIME:"GET_PICK_DROP_TIME",
    REVERSE_PICK_DROP:"REVERSE_PICK_DROP",
    GET_LOCATION_INDEX:"GET_LOCATION_INDEX"
};