# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JHShuttleServiceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JHShuttleServiceApp
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'JHShuttleServiceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'JHShuttleServiceApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JHShuttleServiceApp-tvOS

  target 'JHShuttleServiceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
